# Generated by Django 2.2 on 2022-07-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_defaultuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
